### ISSUE TITLE
Store and check version against user agent

### ISSUE THREAD

**Issue by petemill** [getify/es-feature-tests#1]
How about storing the user-agent and checking against this (at least more often than a couple weeks) when reading the cached data? If the browser gets updated then the user agent will change and we'll catch that.

Thanks!

**Comment by getify** [comment]
hmm... that's an interesting idea. :) do you think browsers will update quickly enough to justify?

**Comment by petemill** [comment]
It could be better to have the most correct results immediately for each
browser version. One reason I can think of is debugging, so that the same
code is being run by the same browser versions.

Plus, if you rely exclusively on comparing current user-agent to stored
user-agent, the 2-week window could be removed. So it's precisely because
browsers most likely update less than once per 2 weeks that this could be
implemented - you would therefore only re-check when the browser is next
updated.

**Comment by getify** [comment]
I have a very strong aversion to user agent string anything. So my initial reaction is to think "absolutely not". There's just far too many ways user agent strings are not reliable.

I'm not entirely sure how I think about using it as a unique fingerprint.

How sure can we be that every single update (even nightly updates) changes the UA string (even on mobile, etc)? What about the user plugins that obscure the UA string for privacy purposes, etc?

**Comment by getify** [comment]
Closing for now. Please re-open if there's more information to consider.
