### ISSUE TITLE
letConst should be false in IE11 & Edge

### ISSUE THREAD

**Issue by mgol** [getify/es-feature-tests#10]
IE11 & Edge don't follow the ES6-mandated rule that a `const`/`let` fresh binding is created for each iteration of the `for` loop. The following is valid ES6 but will throw a `SyntaxError`:

``` js
for (const i in {a: 2, b: 3}) {
    setTimeout(function () {
        console.log(i);
    });
}
```

Even worse, the following will parse correctly:

``` js
for (let i in {a: 2, b: 3}) {
    setTimeout(function () {
        console.log(i);
    });
}
```

but will print `b` twice instead of `a b`.

**Comment by getify** [comment]
AFAIK, `for (const i in {}){}` is not valid because the `const` must have an assignment at declaration time.

**Comment by getify** [comment]
The second loop should work, though. Neither IE nor FF support it yet. Proposed test:

**letConstFor:**

``` js
var x=[], i = -10;
for (let i=0;i<1;i++){x.push(function(){return i})}
for (let i in {1:1}){x.push(function(){return i})}
for (const i=2;i<3;i++){x.push(function(){return i})}
if (x[0]()+x[1]()+x[2]()+x[3]() != 3) throw "";
```

**Note:** currently both chrome and babel seem to syntax-choke on `for (const i=2 ..` I believe this is valid, but checking with @allenwb to verify.

**Comment by mgol** [comment]
> AFAIK, `for (const i in {}){}` is not valid

Are you sure? It used to fail in Chrome, now it passes there. It's also supported by Babel.

**Comment by mgol** [comment]
``` js
for (const i=2;i<3;i++){x.push(function(){return i})}
```

I don't think that's valid; even though you create a fresh `i` const binding per iteration, you invoke `i++` on it which is not allowed. But, IMO you can iterate on arrays this way:

``` js
for (const elem of [2, 3]) {
    console.log(elem);
}
// 2 3
```

I do it all the time in my project and consider it very valuable.

**Comment by mgol** [comment]
See http://www.ecma-international.org/ecma-262/6.0/#sec-for-in-and-for-of-statements-static-semantics-early-errors: two of the syntaxes mentioned are:

```
for ( ForDeclaration in Expression ) Statement
for ( ForDeclaration of AssignmentExpression ) Statement
```

Later on, `ForDeclaration` [is specified](http://www.ecma-international.org/ecma-262/6.0/#sec-for-in-and-for-of-statements-static-semantics-boundnames):

```
ForDeclaration : LetOrConst ForBinding
```

`LetOrConst` is `let` or `const`; also:

```
ForBinding : BindingIdentifier
```

and:

```
BindingIdentifier : Identifier
```

which suggests:

``` js
for ( const i of [2, 3] ) console.log(i);
```

should work.

**Comment by getify** [comment]
**Note:** `letConst` stays `true`, as it's only testing the non-loop declaration forms. I've added 3 new tests: `letLoop`, `constLoop`, and `letLoopScope`.

**Comment by mgol** [comment]
> Note: letConst stays true, as it's only testing the non-loop declaration forms. I've added 3 new tests: letLoop, constLoop, and letLoopScope.

Sounds good. :+1:
