### ISSUE TITLE
Possible bug in parser

### ISSUE THREAD

**Issue by arackaf** [getify/es-feature-tests#19]
The code below is informing my I have a concise method property.  Messing with the whitespace next to request = makes it go away sometimes.  Also, killing the foo() call makes it go away.

``` javascript```
'use strict';

define([], function () {
    _createClass(x, [{
        value: function bulkShare(vm, evt) {
            var y = this.ssr().map(function (item) {
                return item.id;
            }),
                request = {
                resourceIds: y.join(','),
                contactId: ko.unwrap(this.a()),
                contactType: ko.unwrap(this.b())
            };
            foo();
        }
    }]);

    return null;
});
```

**Comment by getify** [comment]
Don't use [bad identation](https://github.com/ternjs/acorn/issues/397#issuecomment-201926138).

**Comment by RReverser** [comment]
@getify Why don't you use proper parser here? I suppose testify is usually executed against finalized JS files?
