### ISSUE TITLE
Test results persist in localStorage after browser is updated

### ISSUE THREAD

**Issue by Rich-Harris** [getify/es-feature-tests#20]
I just updated from Chrome 49 to 50 and expected that the `unicodeRegExp` test would now pass, but it didn't. Clearing `localStorage` fixed it:

![screen shot 2016-04-14 at 11 00 07 am](https://cloud.githubusercontent.com/assets/1162160/14532799/59592f36-0230-11e6-93cb-c2226e813d09.png)

I'd expected that the stored results would include the user agent string (or something?) so that they could be invalidated following an update – what do you reckon?

**Comment by getify** [comment]
The default behavior is to keep tested results for two weeks. No UA string is stored. You can force a manual update (without having to clear out LS through devtools) of the main test results on this page https://featuretests.io/mybrowser clicking "run all tests". Alternatively, you can clear a specific site's caching of the results using: `window["Reflect.supports"].clearLocalSiteCache()`.

**Comment by Rich-Harris** [comment]
Is that desirable though? It means that in order to guarantee correct results, you have to invalidate cached results every time, which defeats the purpose of having a cache. What's the rationale for clearing it after two weeks?

**Comment by getify** [comment]
> It means that in order to guarantee correct results, you have to invalidate

Not exactly. It means that at worst, someone's browser has updated and they aren't taking advantage of the new code for a period of two weeks. On average, that waiting period will probably be around or under a week. Nothing will have broken in the meantime, of course, just simply that browser's test results will lag a little behind the update.

I think responsible use of this library is to let the caching work as designed. You can't predict when people will update, so you shouldn't try to micro-manage it. And there's no real downside to having users progressively "upgrading" to the latest features of a browser over a short period at different intervals.

> What's the rationale for clearing it after two weeks

It's a balance. It could update daily, or even hourly. But how often are normal users likely to update their browsers? Not very often. If we are re-running the tests regularly, we're keeping the test results fresh, but we're also needlessly slowing down pages for users.

Most of the stable browsers only update every six weeks. I initially thought about 6 weeks as the interval, but that seemed too long. 3 weeks would have been reasonable, but I shortened it further to two weeks which seemed like a very reasonable compromise between "every second" and "every six weeks".

**Comment by Rich-Harris** [comment]
Cool. My use case is slightly unusual in that I'm trying to generate a support matrix for use in http://buble.surge.sh. That said though, is there any reason _not_ to use UA strings as a way to detect staleness? No-one is going to get new features supported without also getting a new UA string, after all - I can send a PR if that's helpful?

**Comment by getify** [comment]
If you need to always guarantee getting fresh testing (and the overhead of that is not a concern), I believe you should just always use before retrieving the test results:

``` js
window["Reflect.supports"].disableLocalCache();
```

> is there any reason not to use UA strings as a way to detect staleness?

In general, UA strings are not reliable identifications for browsers. I have a deep objection to building functionality based on them. I kinda wish they'd just go away.

But that bias aside, some users (like me) get UA updates daily (I run chrome canary), and as such, if the caching were based on UA, I'd be unnecessarily getting test results updated every day. This seems like a waste for the general mode of the library for the vast majority of users.

> No-one is going to get new features supported without also getting a new UA string

In general that's probably true, but it's also true that a lot UA string changes happen without giving you new features, so I just don't think it's a good proxy for determining when tests should be re-run.

> I can send a PR if that's helpful?

I would probably not want this feature in the main lib, given my reasons above, and given the fact that you can already manually disable (or empty) the cache if your use-case calls for it.

At a minimum, such a feature would have to be optional, and there'd have to be some reasonable way of selecting whether you wanted to cache based on UA or timestamps. I can imagine there'd be complexities here if someone already has timestamp results in LS and then chooses UA-cached results. I don't want there to be too much complexity introduced just to handle some corner cases. So it'd have to be something that was very simple/elegant to get around.

**Comment by getify** [comment]
It's also important to note that your disabling of the caching or emptying it out is only affecting your site (ie, "local"), not the "global" one on "featuretests.io" that users can share across sites (that use the lib). So, it's totally safe and appropriate for you to use `disableLocalCache()` for your site so that all visitors to your site are getting exactly up-to-date results.

**Comment by Rich-Harris** [comment]
Noted. Thanks for the answers! Will close this issue and use `disableLocalCache()`.
